### ISSUE TITLE
Allow linking non-vendored lz4 and put vendored sources behind a feature

### ISSUE THREAD

**Issue by figsoda** [picoHz/lzzzz#16]
If this is already possible, how do I do that?

**Comment by FollieHiyuki** [comment]
@picoHz I'm also interested in this. Can you look into the issue. Having an option to link to the system `lz4` would be nice.

**Comment by picoHz** [comment]
It's a bit tricky because available features depend on the version of the installed liblz4.
Even if you installed the latest version, some functions are not available in the dynamic-linked version.

**Comment by figsoda** [comment]
maybe we can do features for different versions

**Comment by figsoda** [comment]
still important to me
