### ISSUE TITLE
[Maintenance] Update LZ4 to 1.10.0

### ISSUE THREAD

**Issue by Sewer56** [picoHz/lzzzz#23]
Version 1.10.0 unexpectedly released 1.5 months ago:

- https://github.com/lz4/lz4/releases/tag/v1.10.0

Updating seems like it'd be relatively trivial.
Would you prefer a PR for this?

**Comment by picoHz** [comment]
@Sewer56 
Thank you for the information. Multi-core support sounds great!
Would you be able to create a PR?

**Comment by Sewer56** [comment]
Yup, that's no problem.
I'll get it sorted later today, at least the version bump; hopefully all goes smooth.
