### ISSUE TITLE
function `compress_fast_ext_state()` has a memory issue without pre-checking

### ISSUE THREAD

**Issue by cicilzx** [picoHz/lzzzz#24]
Hi, I'm developing a fuzzer to test the safe abstraction, and I fonnd a invalid memory reference when calling function `lzzzz/src/lz4/block/api/compress_fast_ext_state()`.

Bellow is a test case:
```rust
#[allow(warnings, unused, non_snake_case)]
#[test]
fn test_compress_fast_ext_state_2jfwX() {
    let mut state: [u8; 2usize] = [7, 0];
    let src: [u8; 3usize] = [192, 210, 200];
    let mut dst: Vec<u8> = vec![];
    let dst_len: usize = 10280488706348057135;
    let acceleration: i32 = 1402214550;

    let _ = compress_fast_ext_state(&mut state, &src, dst.as_mut_ptr(), dst_len, acceleration);
}
```
The test result is as follows:
```
Caused by:
  process didn't exit successfully: `/home/cici/lzzzz/target/debug/deps/lzzzz-0ef3d6cc3bfab2d2 'lz4::block::api::test_compress_fast_ext_state_2jfwX' --exact --show-output` (signal: 11, SIGSEGV: invalid memory reference)
```

Even though this function is not a public API, I have checked that the public API `lzzzz::lz4::compress` calling this function also didn't do pre-checking of these parameters. 

Maybe it would be safer to add some pre-conditions or assertions before using the unsafe block, to make sure it wouldn't crash: https://github.com/picoHz/lzzzz/blob/821f4383765890f916934ec5f039752065f25434/src/lz4/block/api.rs#L22

**Comment by picoHz** [comment]
The test case crashes because `dst_len` is invalid.
`lz4::compress` uses `dst.len()` to ensure `dst_len` is vaild.

```
pub fn compress(src: &[u8], dst: &mut [u8], acc: i32) -> Result<usize> {
    compress_to_ptr(src, dst.as_mut_ptr(), dst.len(), acc)
}
```
