### ISSUE TITLE
AsyncReadCompressor is never waked up when buffer too small

### ISSUE THREAD

**Issue by jean-airoldie** [picoHz/lzzzz#5]
It seems that when the read / write buffer is smaller than the total size of the lz4f frame, the `AsyncReadCompressor` is not waked up properly.

Here is my repoduction [example](https://github.com/jean-airoldie/lzzzz_async_read_decompressor/blob/master/examples/never_reads.rs). I'm using my `async_std` branch for simplicity.

**Comment by picoHz** [comment]
Repoduction in `tokio-io` version: https://github.com/picoHz/lzzzz/commit/a00f7864808fcdc6d7fd5d3083704f575b1fe2c4

**Comment by picoHz** [comment]
Close by https://github.com/picoHz/lzzzz/commit/a318259516929ac9894b968c7f7d4784497d7e31

**Comment by jean-airoldie** [comment]
Even with the latest version, the issue still persists. I'll submit PR with some reproduction code tomorrow if I get the time.
